services:
  nextjs:
    image: simonvanmello/next-media-dl:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - nextjs